language: python
python:
  - "2.7"

before_script:
- ls
- pwd
- $PYTHONPATH
- export PYTHONPATH=/home/travis/build/SingaporeClouds/education/google_appengine/
- $PYTHONPATH
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/SingaporeClouds/education/google_appengine/lib/django-1.2/
- $PYTHONPATH
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/SingaporeClouds/education/google_appengine/lib/webapp2-2.5.2/
- $PYTHONPATH
- export PYTHONPATH=$PYTHONPATH:/home/travis/build/SingaporeClouds/education/google_appengine/lib/webob_0_9/
- $PYTHONPATH

# command to install dependencies
install:
  - curl -O http://googleappengine.googlecode.com/files/google_appengine_1.8.1.zip && unzip -q google_appengine_1.8.1.zip
  - pip install webtest
  - pip install pycrypto
# command to run tests
script:  python unittests/test_main.py