language: python
python:
- '2.7'
before_script:
- cd ..
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.2.zip
- unzip -q google_appengine_1.8.2.zip
- rm google_appengine_1.8.2.zip
script:
- git clone https://github.com/SingaporeClouds/education.git
after_success:
- ls
- cd education
- ls
