language: python
python:
  - "2.7"

before_script:
- ls

# command to install dependencies
install:
  - curl -O http://googleappengine.googlecode.com/files/google_appengine_1.8.1.zip && unzip -q google_appengine_1.8.1.zip
  - pip install webtest
  - pip install pyquery
  - pip install pycrypto
  - pip install mock
  - pip install nose
# command to run tests
script:  python unittests/test_main.py